EV-411: Refatoração para atender a Onion Architecture
gpiagentini/CostumerAPI pull request #4
Opened 2022-08-25 13:06 UTC by gpiagentini

### **Jira Tracking**
[EV-411](https://warren.atlassian.net/jira/software/c/projects/EV/boards/454?modal=detail&selectedIssue=EV-411)
### **Description**
Refatoração do código para atender a Onion Architecture e melhorias ao salvar e retornar os clientes.

### **Short description of the changes**

- Biblioteca de classe DomainModel criada;
- Biblioteca de classe DomainServices criada;
- Biblioteca de classe AppServices criada;
- Migração do código presente no projeto WebApi para as bibliotecas de classe;
- Melhorias na criação e retorno de dados de clientes em CustomerService.cs

2022-08-25 14:11 UTC, leonardospaulino requested changes

2022-08-25 14:11 UTC, leonardospaulino commented on AppServices/Interfaces/ICustomerService.cs
> +        public int ProcessNewCustomer(CustomerBase customer);
por padrão ao declarar um metodo via interface ele já vem publico, então ai esta redundante

2022-08-25 14:11 UTC, leonardospaulino commented on CostumersAPI/Controllers/CustomersController.cs
> +        public IActionResult PostNewCustomer(CustomerBase customer)
como aqui é uma controller que trata especificamente de um objeto não tem necessidade de especificar o nome do endpoint, pode aplicar Post, Get, Put, Delete, GetAll

2022-08-25 14:11 UTC, leonardospaulino commented on AppServices/Interfaces/ICustomerService.cs
> +    public interface ICustomerService
Alterar nome para ICustmoerAppService

2022-08-25 17:18 UTC, leonardospaulino requested changes

2022-08-25 17:18 UTC, leonardospaulino commented on CostumersAPI/Controllers/CustomersController.cs
> +                return customers.Count == 0 ? Ok(customers) : NotFound("Nenhum Cliente encontrado!");
tem certeza desse retorno aqui ?

2022-08-25 17:39 UTC, gpiagentini commented on CostumersAPI/Controllers/CustomersController.cs
> +                return customers.Count == 0 ? Ok(customers) : NotFound("Nenhum Cliente encontrado!");
Nossa, confundi na hora de criar o ternário 😥

2022-09-01 16:53 UTC, viniciusoliveira-warren commented on CostumersAPI/CustomersAPI.csproj
> +	  <ProjectReference Include="..\DomainServices\DomainServices.csproj" />
Apenas AppService porque AppService possui referencias aos demais
```suggestion
	  <ProjectReference Include="..\AppServices\AppServices.csproj" />
```

2022-09-01 16:53 UTC, viniciusoliveira-warren commented on CostumersAPI/CustomersAPI.csproj
> +		<PackageReference Include="FluentValidation.AspNetCore" Version="11.2.1" />
Esse pacote podemos remover daqui e levar para AppServices

2022-09-01 16:55 UTC, viniciusoliveira-warren commented on CostumersAPI/Program.cs
> +    .AddSingleton<ICustomerRepository, CustomerService>();
```suggestion
builder.Services.AddTransient<ICustomerAppService, CustomersAppService>();
builder.Services.AddSingleton<ICustomerRepository, CustomerService>();

builder.Services.AddFluentValidationAutoValidation();
```

2022-09-01 16:55 UTC, viniciusoliveira-warren commented on DomainServices/CustomerService.cs
> +        public List<CustomerBase> _inMemoryCustomers = new List<CustomerBase>();
```suggestion
    public class CustomerService : ICustomerRepository
    {
        public List<CustomerBase> _inMemoryCustomers = new List<CustomerBase>();
```

2022-09-01 16:55 UTC, viniciusoliveira-warren commented on DomainServices/CustomerService.cs
> +        public int CreateNew(CustomerBase customer)
```suggestion
        public int Add(CustomerBase customer)
```

2022-09-05 16:33 UTC, ghost commented on AppServices/AppServices.csproj
> +		<ProjectReference Include="..\DomainModels\DomainModels.csproj" />
Quem faz referencia a DomainModels é a camada de aplicação
```suggestion
```

2022-09-05 16:36 UTC, viniciusoliveira-warren commented on CostumersAPI/Program.cs
> +builder.Services.AddScoped<IValidator<CustomerBase>, NewCustomersValidator>();
NewCustomers? estamos adicionando mais de 1? se não o correto é NewCustomerValidator
```suggestion
builder.Services.AddValidatorsFromAssemblyContaining<NewCustomersValidator>();
```

2022-09-05 16:37 UTC, viniciusoliveira-warren commented on DomainModels/EntityBase.cs
> +    }
Sendo uma classe exclusiva temos 2 opções a se fazer

1. Transformar classe em abstract
2. Transformar em interface

2022-09-05 16:38 UTC, viniciusoliveira-warren commented on DomainServices/CustomerService.cs
> +            customer.Id = _inMemoryCustomers.LastOrDefault() != null ? _inMemoryCustomers.LastOrDefault().Id + 1 : 1;
```suggestion
            customer.Id = _inMemoryCustomers.Any() ? _inMemoryCustomers.LastOrDefault().Id + 1 : 1;
```

2022-09-05 16:38 UTC, ghost commented on DomainServices/CustomerService.cs
> +        public List<CustomerBase> _inMemoryCustomers = new List<CustomerBase>();
```suggestion
        private readonly List<CustomerBase> _inMemoryCustomers = new();
```

2022-09-05 16:39 UTC, viniciusoliveira-warren commented on DomainServices/CustomerService.cs
> +            var customerToRemove = _inMemoryCustomers.Where(customer => customer.Id == id).FirstOrDefault();
```suggestion
            var customerToRemove = _inMemoryCustomers.FirstOrDefault(customer => customer.Id == id);
```

2022-09-05 16:39 UTC, viniciusoliveira-warren commented on DomainServices/CustomerService.cs
> +            }
```suggestion
            updatedCustomer.Id = customerToUpdate.Id;
            var index = _inMemoryCustomers.IndexOf(customerToUpdate);
            _inMemoryCustomers[index] = updatedCustomer;
```

2022-09-05 16:42 UTC, ghost commented on DomainServices/CustomerService.cs
> +        public void Update(int id, CustomerBase updatedCustomer)
Chamar de Updated nos diz que já foi atualizado o que não seria o caso aqui, o correto seria chamar customerToUpdate
```suggestion
        public void Update(int id, CustomerBase updatedCustomer)
```

2022-09-05 16:58 UTC, viniciusoliveira-warren commented on DomainServices/CustomerService.cs
> +        public void Update(int id, CustomerBase updatedCustomer)
Como aqui já estamos na camada de domínio o Id já deveria estar dentro da entidade e não separado

2022-09-05 17:18 UTC, viniciusoliveira-warren commented on DomainServices/CustomerService.cs
> +            if (customerToUpdate == null) throw new ArgumentOutOfRangeException();
ArgumentOutOfRangeException é usado para quando tentamos acessar um index negativo ou um valor além do que aquela lista possui. A exceção correta para se usar aqui é ArgumentException

[documentação do ArgumentOutOfRangeException](https://docs.microsoft.com/pt-br/dotnet/api/system.argumentoutofrangeexception?view=net-6.0)
[documentação do ArgumentException](https://docs.microsoft.com/pt-br/dotnet/api/system.argumentexception?view=net-6.0)

2022-09-05 17:38 UTC, gpiagentini commented on CostumersAPI/Program.cs
> +builder.Services.AddScoped<IValidator<CustomerBase>, NewCustomersValidator>();
Poderia utilizar dessa forma?

```suggestion
builder.Services.AddValidatorsFromAssembly(Assembly.Load(nameof(AppServices)));
```

2022-09-05 17:43 UTC, gpiagentini commented on DomainModels/EntityBase.cs
> +    }
Transformei classe em abstrata

2022-09-06 16:46 UTC, viniciusoliveira-warren approved these changes

2022-09-06 16:50 UTC, merged